export const profileText = {
  'zh-TW': {
    upload: '上傳內容',
    posts: '貼文',
    followers: '粉絲',
    editProfile: '編輯檔案',
    shareProfile: '分享檔案',
    notifications: '通知',
    settings: '設定',
    analytics: '流量報告',
    archive: '典藏內容',
    membership: 'Vibe會員',
    account: '帳號管理',
    favorites: '我的收藏',
    public: '公開',
    private: '不公開',
    featuredStories: '精選限動',
    noVideos: '尚無短影片',
    cancel: '取消',
    save: '儲存',
    uploading: '上傳中...',
    changeAvatar: '更換頭像',
    displayName: '顯示名稱',
    displayNamePlaceholder: '輸入顯示名稱',
    username: '使用者ID',
    usernamePlaceholder: '輸入 username',
    bio: '自我介紹',
    bioPlaceholder: '輸入自我介紹',
  },

  en: {
    upload: 'Upload',
    posts: 'Posts',
    followers: 'Followers',
    editProfile: 'Edit Profile',
    shareProfile: 'Share Profile',
    notifications: 'Notifications',
    settings: 'Settings',
    analytics: 'Analytics',
    archive: 'Archive',
    membership: 'Vibe Membership',
    account: 'Account',
    
    favorites: 'My Favorites',
    public: 'Public',
    private: 'Private',
    featuredStories: 'Story Highlights',
    noVideos: 'No short videos yet',
    cancel: 'Cancel',
    save: 'Save',
    uploading: 'Uploading...',
    changeAvatar: 'Change Avatar',
    displayName: 'Display Name',
    displayNamePlaceholder: 'Enter display name',
    username: 'Username',
    usernamePlaceholder: 'Enter username',
    bio: 'Bio',
    bioPlaceholder: 'Enter your bio',
  },
} as const